### PR TITLE
Add more tests for properties `selections` and `selectionList`

### PR DESCRIPTION
**Pull request by hangxingliu**
Add more integration tests for the PR #498 

These tests can be also treated as an incomplete spec of the new property `selectionList`.

### CODE REVIEW

**Comment by hangxingliu** [comment]
@ndrsn I will push one more commit into this PR tonight. It doesn't need to be megred now. Thanks

**Comment by hangxingliu** [comment]
Thanks for @velitasali , He found I declared the function `fitSelectedColumns` two times in the source code. I will remove duplicated declaration tonight too.

**Comment by ndrsn** [comment]
> @ndrsn I will push one more commit into this PR tonight. It doesn't need to be megred now. Thanks

I think if you make this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/), we can prevent my fat fingers from accidentally hitting the merge button until it's ready :-)

**Comment by hangxingliu** [comment]
> I think if you make this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/), we can prevent my fat fingers from accidentally hitting the merge button until it's ready :-)

Oh, thanks for your tip. To be honest, I used Github for very long time, but this is my first time to know about it.

**Comment by hangxingliu** [comment]
@ndrsn  By the way, the code about the selection feature has not reached the end. I will work on the cache of it and optimize the adaptor for old API. And fix bugs if anybody report the bug about it. Then I will create another PR for them. But this optimization needs some time.   
But now it can works well and it improves performance although it is not its best performance, I tested it with 1 million rows and its selection experience is very good now

I see that @velitasali has worked on some features related to the selection. I think you can release them and this new selection mechanism in next MINOR version (0.5.0)

**Comment by ndrsn** [comment]
All good!

🎉

**Pull request merged**
