### PR TITLE
change frozen style like google spreadsheet

### PR DESCRIPTION
**Pull request by xianzhi3**
Hi, @ndrsn I changed the frozen style like google spreadsheet.
You can have a test at the link below.
https://90zfd.csb.app/demo.html

### CODE REVIEW

**Comment by ndrsn** [comment]
Hi @xianzhi3 thanks for this. I believe I've discovered two bugs/quirks. For now I can only reproduce the one below here:

CleanShot 2022-02-07 at 23 30 23

I'll see if I can narrow down the other later this week.

**Comment by xianzhi3** [comment]
@ndrsn I fixed the quirks bug

**Comment by ndrsn** [comment]
Hi! Great! I managed to reproduce the other one. The recording is a bit long, because I'm not sure which parts of it are relevant, but here is the weird behavior:

CleanShot 2022-02-16 at 22 28 55

**Comment by hangxingliu** [comment]
@ndrsn @xianzhi3 Hi everyone, I guess the bug that Jona metioned has been fix in #480  I can confirm it with you after I wake up.

**Comment by mdebrauw** [comment]
Hi @xianzhi3 I (visually) tested this too using the link you provided.

Still seeing some weird behaviour, sudden and fast mouse movements seem to make the grid disappear for a moment.

CleanShot 2022-02-18 at 13 58 24

**Comment by xianzhi3** [comment]
It works well in my end. What is your computer OS?

**Comment by mdebrauw** [comment]
Chrome Version 98.0.4758.80 (Official Build) (arm64) on macOs Monetery (12.0)

**Comment by ndrsn** [comment]
I can reproduce this as well — see the white screen near the end of the animation. Only once I move the mouse again the grid re-renders:

CleanShot 2022-02-19 at 15 48 34

**Comment by ndrsn** [comment]
Another one:

CleanShot 2022-02-19 at 16 08 05

**Comment by hangxingliu** [comment]
I think the key to reproduce this bug is:

Drag the frozen marker and let your mouse leave the browser, then backed to the grid. 

And the grid is empty(only has white background) until you move your mouse to trigger next render.

**Comment by ndrsn** [comment]
> You drag the frozen marker and let your mouse leave the browser, then backed to the grid.

Maybe that one edge-case, but in this example I don't leave the browser boundaries:

CleanShot 2022-02-19 at 22 27 13

(Apologies for the million open tabs, I am seeking professional help)

**Comment by hangxingliu** [comment]
@ndrsn can you have a test on this demo: https://9l3dgo.csb.app/

the changes between the demo and the latest commit of this PR are here:

Screenshot 2022-02-21 at 04 52 01

(btw, you may can try the extension named `OneTab` or `Better OneTab` for organizing the tabs)

**Comment by ndrsn** [comment]
@hangxingliu that seemed to work, thanks! But why, though? The behaviour seemed a little flaky/inconsistent, and it's not clear to me how this fix explains what was happening.

I'll be happy to merge this (including your fix), and don't want to cause anyone more work, but if you or @xianzhi3 can explain what the bug _was_ and why this change is the fix we need, I'll be a little more confident in merging :-)

**Comment by hangxingliu** [comment]
@ndrsn I am not 100 percent sure my guess is correct. If I need to explain to you, I need another test for this bug. But I am working on the refactoring of `self.selections` for performance purpose (On another branch with unstaged changes). I can test it again and tell you after I finished the util functions of it.

**Comment by ndrsn** [comment]
@hangxingliu That sounds reasonable! Do you suggest we merge this now? If this is part of the code you guys will be touching anyway, I trust any lingering bugs will be ironed out anyway :-)

**Comment by hangxingliu** [comment]
@ndrsn The investigation of this bug is almost done, I will write it in the Slack channel one message by one message. I think you can merge this PR and the patch after you read them.

**Comment by ndrsn** [comment]
Alright! @xianzhi3 can you fix the merge conflicts? Then I'll merge right after.

**Comment by ndrsn** [comment]
Great work @xianzhi3 and @hangxingliu, thanks a lot!

**Pull request merged**
