### PR TITLE
add feature to move a cell or range of cells

### PR DESCRIPTION
**Pull request by xianzhi3**
Here is a link for test
https://90zfd.csb.app/413.html

### CODE REVIEW

**Review by ndrsn — CHANGES_REQUESTED** [review]
I'm not sure this PR is fully complete, yet? Is the intention here to _only_ modify the viewed data, which may change at any time, not the underlying original data?

I would imagine that when you're moving a bunch of data around in a spreadsheet, the user would want the original data changed as well, not just what's painted on the screen.

Would you not need to modify  `originalData` then as well? And, preferably, also emit the moved cells in an (`endmove`?) event?

**Comment by xianzhi3** [comment]
> I'm not sure this PR is fully complete, yet? Is the intention here to _only_ modify the viewed data, which may change at any time, not the underlying original data?
> 
> I would imagine that when you're moving a bunch of data around in a spreadsheet, the user would want the original data changed as well, not just what's painted on the screen.
> 
> Would you not need to modify `originalData` then as well? And, preferably, also emit the moved cells in an (`endmove`?) event?

**Comment by xianzhi3** [comment]
Ok

**Comment by xianzhi3** [comment]
Ok, let me check

**Comment by hangxingliu** [comment]
Hi @ndrsn @xianzhi3 , I think this PR can be closed. I am refactoring the selection feature of this grid. So the code in this PR will be replaced in the next PR. I am going to sleep now and I will create a new PR in the next week

**Comment by ndrsn** [comment]
Alright, thanks for the update!

**Pull request closed without merging**
