### PR TITLE
Fix missing text where value has multiple '-'

### PR DESCRIPTION
**Pull request by faimaklg**
where row value has multiple '-', the cell show only before '-';
image
image

### CODE REVIEW

**Comment by TonyGermaneri** [comment]
THANK YOU!!

**Comment by faimaklg** [comment]
Can a version be released

**Comment by TonyGermaneri** [comment]
https://github.com/TonyGermaneri/canvas-datagrid/releases/tag/v0.3.5

**Comment by faimaklg** [comment]
image

**Comment by TonyGermaneri** [comment]
Ok, hope this time it works.  Forgot to tick the package number.

**Comment by faimaklg** [comment]
https://www.npmjs.com/package/canvas-datagrid?activeTab=versions

**Comment by TonyGermaneri** [comment]
```tonygermaneri@fa00637 canvas-datagrid % npm publish
npm notice
npm notice 📦  canvas-datagrid@0.3.5
npm notice === Tarball Contents ===
npm notice 1.5kB  LICENSE
npm notice 7.0kB  lib/component.js
npm notice 24.4kB lib/contextMenu.js
npm notice 13.9kB lib/defaults.js
npm notice 74.1kB lib/docs.js
npm notice 22.6kB lib/dom.js
npm notice 65.7kB lib/draw.js
npm notice 55.5kB lib/events.js
npm notice 46.7kB lib/intf.js
npm notice 4.2kB  lib/main.js
npm notice 44.4kB lib/publicMethods.js
npm notice 16.2kB lib/touch.js
npm notice 3.4kB  package.json
npm notice 4.8kB  CHANGELOG.md
npm notice 7.0kB  README.md
npm notice === Tarball Details ===
npm notice name:          canvas-datagrid
npm notice version:       0.3.5
npm notice package size:  80.8 kB
npm notice unpacked size: 391.4 kB
npm notice shasum:        a64a454537014aa229c50ea12faad6029ca63ec9
npm notice integrity:     sha512-sh4tHTWscMFf8[...]Onua0VPBml77w==
npm notice total files:   15
npm notice
+ canvas-datagrid@0.3.5```

Seems to have published correctly but I don't see it on NPM.

Tried to publish again:

```
tonygermaneri@fa00637 canvas-datagrid % npm publish
npm notice
npm notice 📦  canvas-datagrid@0.3.5
npm notice === Tarball Contents ===
npm notice 1.5kB  LICENSE
npm notice 7.0kB  lib/component.js
npm notice 24.4kB lib/contextMenu.js
npm notice 13.9kB lib/defaults.js
npm notice 74.1kB lib/docs.js
npm notice 22.6kB lib/dom.js
npm notice 65.7kB lib/draw.js
npm notice 55.5kB lib/events.js
npm notice 46.7kB lib/intf.js
npm notice 4.2kB  lib/main.js
npm notice 44.4kB lib/publicMethods.js
npm notice 16.2kB lib/touch.js
npm notice 3.4kB  package.json
npm notice 4.8kB  CHANGELOG.md
npm notice 7.0kB  README.md
npm notice === Tarball Details ===
npm notice name:          canvas-datagrid
npm notice version:       0.3.5
npm notice package size:  80.8 kB
npm notice unpacked size: 391.4 kB
npm notice shasum:        a64a454537014aa229c50ea12faad6029ca63ec9
npm notice integrity:     sha512-sh4tHTWscMFf8[...]Onua0VPBml77w==
npm notice total files:   15
npm notice
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/canvas-datagrid - You cannot publish over the previously published versions: 0.3.5.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tonygermaneri/.npm/_logs/2021-08-16T02_49_32_882Z-debug.log
```

Maybe the page is cached?  Not sure.  Maybe it works now?

**Comment by faimaklg** [comment]
now It's right. thanks

**Pull request merged**
