### PR TITLE
Render crisp lines/strokes

### PR DESCRIPTION
**Pull request by tmaroschik**
The middle of lines/strokes on canvas is positioned exactly in between two pixels. This is explained here https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors#A_lineWidth_example

This leads to blurry and too thick lines. 1 px solid black grid lines are displayed as 2 px lines in medium grey. This is somewhat mitigated when lines overlay each other.

The fix attempts to shift all canvas coordinates by half a pixel via the `canvasOffsetTop` and `canvasOffsetLeft` properties.

### CODE REVIEW

**Comment by tmaroschik** [comment]
I'll try to fix the failing tests. Obviously some coordinates shifted by half a pixel now.

**Comment by tmaroschik** [comment]
Ok. Tests pass now. Please check if this is fine.

**Comment by ndrsn** [comment]
Excellent! Thanks, @tmaroschik!

**Comment by ndrsn** [comment]
Released this into v0.24.2 🎉

**Pull request merged**
