### PR TITLE
fix Highlighting incorrect column after repositioning column

### PR DESCRIPTION
**Pull request by xianzhi3**
Fixes issue #.

Changes proposed in this pull request:

- 
- 
-

### CODE REVIEW

**Comment by xianzhi3** [comment]
fixed errors #392 and #394

**Comment by xianzhi3** [comment]
fixed errors #392 and #394

**Comment by ndrsn** [comment]
Hi @xianzhi3, thank you for this. The test suite is currently failing on this; please ensure existing tests run succesfully, and any change in functionality is covered by new tests. I will then review the pull request.

Also, if you can, please read the new (like, few-hours-old new :) [guide for contributing](https://github.com/TonyGermaneri/canvas-datagrid/blob/master/CONTRIBUTING.md)

**Comment by xianzhi3** [comment]
fix #392 issue

**Comment by ndrsn** [comment]
Hi @xianzhi3 , could you please not close and re-open like this?

**Comment by xianzhi3** [comment]
> Hi @xianzhi3 , could you please not close and re-open like this?

sorry, for the mistake

**Comment by david542542** [comment]
@ndrsn Sorry I'll make sure that moving forward @xianzhi3's commits/PRs are properly done and pass all tests, etc. For this first one do you want a new PR made, or is this existing 399 request good?

**Comment by ndrsn** [comment]
Hey @david542542 and @xianzhi3, don't worry and apologies! I was in a cranky mood, it's all good 😊 

I reviewed the code and everything seems alright, so I'll merge this — thank you!

If possible, I would like to make one request though: with future pull requests, is there any way you could link to an online working version of the grid including the proposed changes? As in, host the newly built `canvas-datagrid.js` file with an `index.html` showing a small sample grid — I tried to set one up in CodeSandbox but it took me more than 20 minutes and I couldn't get it working, so I gave up (🤦‍♂️) and did it locally, but if you could prepare something like a CodeSandbox or JS Fiddle with the new version, that would make our lives infinitely easier and review times shorter — reviewing the PR would then mostly be a matter of reading through the changes to see if anything stands, ensuring the tests are there/proper, and clicking around in the grid like the monkey that I am to see if anything breaks.

(Ideally, I would want a pull request to trigger a GitHub action that sets this up automatically, but ugh only 24 hours in a day)

**Comment by xianzhi3** [comment]
ok let me try

**Pull request merged**
