### PR TITLE
Ability to hide rows/cols

### PR DESCRIPTION
**Pull request by hangxingliu**
Related issue #420 

- The document about this feature: https://github.com/hangxingliu/canvas-datagrid-patch/tree/master/docs/feature-420
- Latest CodeSanbox demo: <https://myujs.csb.app/> 

And this PR doesn't need to be merged now. I am still adding the UI tests and documents for it. I create a PR first for everyone can have a look now. And you can leave messages here if you find any bugs with this new feature. Thanks

### CODE REVIEW

**Comment by hangxingliu** [comment]
@ndrsn This commit <https://github.com/TonyGermaneri/canvas-datagrid/pull/480/commits/9513be0b2554dde09b284fbd2427cbe18ad20e09> is used to for fixing this bug:

https://user-images.githubusercontent.com/4303130/151725397-d3f77b55-ca0f-456f-9c79-678823d572c7.mov

This bug causes hidden columns to look weird when the user moves the frozen marker.

**Comment by ndrsn** [comment]
@hangxingliu I'm a little tied up this week, but can look early next, unless @TonyGermaneri wants to review it?

**Comment by ndrsn** [comment]
@hangxingliu, thanks a lot for this — this is great work, and I really appreciate the effort you've put into the tests.

Beyond nitpick-stuff (which I won't mention because it's not important), I found nothing worth mentioning. It all looks pretty good. (Although the only nitpick I might mention would be to add some more more vertical spacing, i.e. empty lines, here and there to separate some of the logical blocks for legibility).

It is, tough, _a lot_ of code, so while I've tried to go through it diligently I may have missed some things. If so: apologies :-)

**Comment by hangxingliu** [comment]
@ndrsn Thanks for your appreciation and your work. And you can leave the comments on the code for me if you want. Because sometimes I am focus on the the logic of the code but forget about legibility.

**Pull request merged**
